---
result_playlists:
  best_matches:
    order: 0
    name: "Best Matches"
    n_songs: 50
    #similitude_range: [1.0, 0.70]
    artist_in_fav_pl_are_included: True
    #use_ml: False
  worth_listening:
   order: 1
   name: "Fuzzy Stuff"
   n_songs: 60
   #similitude_range: [0.7, 0.35] # overlap on purpose, but this playlist MUST be placed always after best matches playlist. this way fuzzy will pick up songs with hi simil that were left out in best matches because of n songs limit
   artist_in_fav_pl_are_included: False
   #use_ml: False    
origin_playlists:
  reference_playlist_url: 
    - "https://open.spotify.com/playlist/6NyjTAYxzLqkPmMY4Z7Lhq?si=0cad74ec1cc0482a"
  playlists_to_curate:
    - "https://open.spotify.com/playlist/1p3CmyfXVeVk3ckO443prf?si=db6bb8c6dd6040b2" # hot hits uk
    - "https://open.spotify.com/playlist/3ivSu20CWXjveS2h2qZ54K?si=2dfcf9865bbc4501" # ready for the weekend
    - "https://open.spotify.com/playlist/5FJ5R13o9A1l018qE0vI88?si=3c139f246c8340d3" # capitan demo
    - "https://open.spotify.com/playlist/5NsZabBjLrejTFijmLwKV2?si=ed983c97348b48cb" # spain new wave
    - "https://open.spotify.com/playlist/3Di88mvYplBtkDBIzGLiiM?si=6d4529e2d42846a1" # edm hits
    - "https://open.spotify.com/playlist/5OVTqQiUOuQoGhpC24sZWd?si=6fa97b7f934f43dc" # fresh finds indie
    - "https://open.spotify.com/playlist/5bs8K6Gr5T0Q0HzrAlkknp?si=914bf6707e8449d9" # fresh finds indie 2
    - "https://open.spotify.com/playlist/3W5wa32sNQR0voyAJZRiSJ?si=f14e2aad0edb4e37" # fresh finds rock 2      
    - "https://open.spotify.com/playlist/4EhjPLkcbWraBhx48IYRt1?si=CxbklQaoScG6Rj8GIb16cw" # more rock 
    - "https://open.spotify.com/playlist/22XHJsFcjUYZi84RzkMPr2?si=4c7e7c09ec564215" # popurri de la semana
    - "https://open.spotify.com/playlist/5NsZabBjLrejTFijmLwKV2?si=60762056b2004074" # spain wave
    - "https://open.spotify.com/playlist/4y4RsISHK5TvJThOSKPnBI?si=702f8bc53a5e4161" # fc25 pl
    - "https://open.spotify.com/playlist/0okFxg6e3F3oZSZGq8kwY0?si=fcfa22ba530a428d" # radar joven
    - "https://open.spotify.com/playlist/6s4HdPQQMfyAkSC2wrotE3?si=d0411b2681b5474f" # primavera 2025
    - "https://open.spotify.com/playlist/4BSj7IwrHLRpZeVNodMh5Z?si=830dece7523a46ad" # coachella 2025

    - "https://open.spotify.com/playlist/47MSXsGaZvarTjtPmVxJTK?si=f9c7d058cdfa4f5e" # new british rock
    - "https://open.spotify.com/playlist/51GmtQuA0j1AlsKgJuEWFB?si=d54c5ca238f24267"
    - "https://open.spotify.com/playlist/2PWmcL6SZx1dm9bZpoXCEE?si=70fb580d61404ef5"
    - "https://open.spotify.com/playlist/6ocDItVfvO3mU4RSsRpGW6?si=165088cb9f004101"
    - "https://open.spotify.com/playlist/5yNdi4PoYD15eXEB7g6XYF?si=89bb161185084d23"
    - "https://open.spotify.com/playlist/52dFMsBJKSnBFLEKW0OB2g?si=73c8bd096ee442cc"
    - "https://open.spotify.com/playlist/0yECGr3NGaW4mw3lsNGskL?si=6823c6a3d6b744f9"
    - "https://open.spotify.com/playlist/2Qu8wxZ3Bbs4a1UJYbwYWj?si=6f93a7785d864a75"
    - "https://open.spotify.com/playlist/1mJFggQPFQHv8K2V8Rv768?si=253baa356cf243ec"
    - "https://open.spotify.com/playlist/2ixwcMhkBf6t5f94IFjoun?si=0a75bd430a3b47ca"
    - "https://open.spotify.com/playlist/7b2JALoATysii4mbkO44bx?si=1f0eadbf594b49d0" 
    - "https://open.spotify.com/playlist/2kJEOAOcSDn6NeksnARkp8?si=a703be0b76124dc5"
     
faved_artists:
  min_songs_in_fav_pl: 3 # artists need to have at least this number of songs in fav pl to be considered (= 1 can create noise)
  fav_playlists_url: 
    - "https://open.spotify.com/playlist/0Zu81wbBbw1B0onTyVYpLN?si=f75b4124e46144b8" # my favs pl
    - "https://open.spotify.com/playlist/7eSCDwgV6yHpuawWURu8qD?si=f16b42eff58f4136" # outliers pl
positive_class_pl: "https://open.spotify.com/playlist/7zbRh4zP0SVtviSYoqn9DM?si=12e7335b56164880"
user: "1199533427"
#max_simil_comparisons: -1 # -1 = all reference songs are kept
#ml_metric_thresh: 0.80 # metric = aucpr
