---
result_playlists:
  best_matches: # this is a playlist name
    name: "Best Matches"
    n_songs: 16
    similitude_range: [1.0, 0.5]
    artist_in_fav_pl_are_included: True
  worth_listening:
    name: "Fuzzy Stuff"
    n_songs: 20
    similitude_range: [0.5, 0.2]
    artist_in_fav_pl_are_included: True
origin_playlists:
  reference_playlist_url: 
    - "https://open.spotify.com/playlist/6NyjTAYxzLqkPmMY4Z7Lhq?si=0cad74ec1cc0482a"
  playlists_to_curate:
    - "https://open.spotify.com/playlist/37i9dQZF1DWY4lFlS4Pnso?si=f6354486afa142e2" # hot hits uk
    - "https://open.spotify.com/playlist/3ivSu20CWXjveS2h2qZ54K?si=2dfcf9865bbc4501" # ready for the weekend
    - "https://open.spotify.com/playlist/5FJ5R13o9A1l018qE0vI88?si=3c139f246c8340d3" # capitan demo
    - "https://open.spotify.com/playlist/5NsZabBjLrejTFijmLwKV2?si=ed983c97348b48cb" # spain new wave
    - "https://open.spotify.com/playlist/2yq4iaXGrLa69oHXGm9olQ?si=3a115915e15b41ee" # primavera sound 2024
faved_artists:
  min_songs_in_fav_pl: 3 # artists need to have at least this number of songs in fav pl to be considered (= 1 can create noise)
  fav_playlists_url: 
    - "https://open.spotify.com/playlist/0Zu81wbBbw1B0onTyVYpLN?si=f75b4124e46144b8"
user: "1199533427"
max_simil_comparisons: 3